/* Generated by re2c 4.1 on Thu Aug 14 21:54:57 2025 */
#line 1 "../../lnav/src/log_level_re.re"
/**
 * Copyright (c) 2018, Timothy Stack
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * * Neither the name of Timothy Stack nor the names of its contributors
 * may be used to endorse or promote products derived from this software
 * without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ''AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "config.h"

#include <string.h>

#include "log_level.hh"

log_level_t string2level(const char *levelstr, ssize_t len, bool exact)
{
    log_level_t retval = LEVEL_UNKNOWN;

    if (len == (ssize_t)-1) {
        len = strlen(levelstr);
    }

    if (((len == 1) || ((len > 1) && (levelstr[1] == ' '))) &&
        (retval = abbrev2level(levelstr, 1)) != LEVEL_UNKNOWN) {
        return retval;
    }

#   define YYCTYPE unsigned char
#   define RET(tok) { \
        return tok; \
    }

    const YYCTYPE *YYCURSOR = (const unsigned char *) levelstr;
    const YYCTYPE *YYLIMIT = (const unsigned char *) levelstr + len;
    const YYCTYPE *YYMARKER = YYCURSOR;
    const YYCTYPE *debug_level = nullptr;

#   define YYPEEK()    (YYCURSOR < YYLIMIT ? *YYCURSOR : 0)
#   define YYSKIP()    ++YYCURSOR
#   define YYBACKUP()  YYMARKER = YYCURSOR
#   define YYRESTORE() YYCURSOR = YYMARKER
#   define YYSTAGP(x)  x = YYCURSOR - 1

    
#line 69 "../../lnav/src/log_level_re.cc"
#line 65 "../../lnav/src/log_level_re.re"

    loop:
    
#line 74 "../../lnav/src/log_level_re.cc"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	yych = YYPEEK();
	if (yych <= 'W') {
		if (yych <= 'K') {
			if (yych <= 'D') {
				if (yych <= 0x00) goto yy1;
				if (yych <= 'B') goto yy2;
				if (yych <= 'C') goto yy4;
				goto yy5;
			} else {
				if (yych <= 'F') {
					if (yych <= 'E') goto yy6;
					goto yy7;
				} else {
					if (yych == 'I') goto yy8;
					goto yy2;
				}
			}
		} else {
			if (yych <= 'R') {
				if (yych <= 'L') goto yy9;
				if (yych == 'N') goto yy10;
				goto yy2;
			} else {
				if (yych <= 'T') {
					if (yych <= 'S') goto yy11;
					goto yy12;
				} else {
					if (yych <= 'U') goto yy2;
					if (yych <= 'V') goto yy13;
					goto yy14;
				}
			}
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'e') {
				if (yych <= 'b') goto yy2;
				if (yych <= 'c') goto yy4;
				if (yych <= 'd') goto yy5;
				goto yy6;
			} else {
				if (yych <= 'h') {
					if (yych <= 'f') goto yy7;
					goto yy2;
				} else {
					if (yych <= 'i') goto yy8;
					if (yych <= 'k') goto yy2;
					goto yy9;
				}
			}
		} else {
			if (yych <= 's') {
				if (yych == 'n') goto yy10;
				if (yych <= 'r') goto yy2;
				goto yy11;
			} else {
				if (yych <= 'u') {
					if (yych <= 't') goto yy12;
					goto yy2;
				} else {
					if (yych <= 'v') goto yy13;
					if (yych <= 'w') goto yy14;
					goto yy2;
				}
			}
		}
	}
yy1:
	YYSKIP();
#line 74 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_UNKNOWN); }
#line 149 "../../lnav/src/log_level_re.cc"
yy2:
	YYSKIP();
yy3:
#line 102 "../../lnav/src/log_level_re.re"
	{ goto loop; }
#line 155 "../../lnav/src/log_level_re.cc"
yy4:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'R') goto yy15;
	if (yych == 'r') goto yy15;
	goto yy3;
yy5:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'E') goto yy17;
	if (yych == 'e') goto yy17;
	goto yy3;
yy6:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'R') goto yy18;
	if (yych == 'r') goto yy18;
	goto yy3;
yy7:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'A') goto yy19;
	if (yych == 'a') goto yy19;
	goto yy3;
yy8:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'N') goto yy20;
	if (yych == 'n') goto yy20;
	goto yy3;
yy9:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'O') goto yy21;
	if (yych == 'o') goto yy21;
	goto yy3;
yy10:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'O') goto yy22;
	if (yych == 'o') goto yy22;
	goto yy3;
yy11:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych <= 'Y') {
		if (yych <= 'S') {
			if (yych == 'E') goto yy23;
			goto yy3;
		} else {
			if (yych <= 'T') goto yy24;
			if (yych <= 'X') goto yy3;
			goto yy25;
		}
	} else {
		if (yych <= 's') {
			if (yych == 'e') goto yy23;
			goto yy3;
		} else {
			if (yych <= 't') goto yy24;
			if (yych == 'y') goto yy25;
			goto yy3;
		}
	}
yy12:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'R') goto yy26;
	if (yych == 'r') goto yy26;
	goto yy3;
yy13:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'E') goto yy27;
	if (yych == 'e') goto yy27;
	goto yy3;
yy14:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'A') goto yy28;
	if (yych == 'a') goto yy28;
	goto yy3;
yy15:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'I') goto yy29;
	if (yych == 'i') goto yy29;
yy16:
	YYRESTORE();
	if (yyaccept <= 1) {
		if (yyaccept == 0) goto yy3;
		else goto yy33;
	} else {
		goto yy59;
	}
yy17:
	YYSKIP();
	yych = YYPEEK();
	if (yych <= 'P') {
		if (yych == 'B') goto yy30;
		if (yych <= 'O') goto yy16;
		goto yy31;
	} else {
		if (yych <= 'b') {
			if (yych <= 'a') goto yy16;
			goto yy30;
		} else {
			if (yych == 'p') goto yy31;
			goto yy16;
		}
	}
yy18:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'R') goto yy32;
	if (yych == 'r') goto yy32;
	goto yy16;
yy19:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'T') goto yy34;
	if (yych == 't') goto yy34;
	goto yy16;
yy20:
	YYSKIP();
	yych = YYPEEK();
	if (yych <= 'V') {
		if (yych == 'F') goto yy35;
		if (yych <= 'U') goto yy16;
		goto yy36;
	} else {
		if (yych <= 'f') {
			if (yych <= 'e') goto yy16;
			goto yy35;
		} else {
			if (yych == 'v') goto yy36;
			goto yy16;
		}
	}
yy21:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'G') goto yy37;
	if (yych == 'g') goto yy37;
	goto yy16;
yy22:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'T') goto yy38;
	if (yych == 't') goto yy38;
	goto yy16;
yy23:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'V') goto yy39;
	if (yych == 'v') goto yy39;
	goto yy16;
yy24:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'A') goto yy40;
	if (yych == 'a') goto yy40;
	goto yy16;
yy25:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'S') goto yy41;
	if (yych == 's') goto yy41;
	goto yy16;
yy26:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'A') goto yy42;
	if (yych == 'a') goto yy42;
	goto yy16;
yy27:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'R') goto yy43;
	if (yych == 'r') goto yy43;
	goto yy16;
yy28:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'R') goto yy44;
	if (yych == 'r') goto yy44;
	goto yy16;
yy29:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'T') goto yy45;
	if (yych == 't') goto yy45;
	goto yy16;
yy30:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'U') goto yy46;
	if (yych == 'u') goto yy46;
	goto yy16;
yy31:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'R') goto yy47;
	if (yych == 'r') goto yy47;
	goto yy16;
yy32:
	yyaccept = 1;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'O') goto yy48;
	if (yych == 'o') goto yy48;
yy33:
#line 97 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_ERROR); }
#line 393 "../../lnav/src/log_level_re.cc"
yy34:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'A') goto yy49;
	if (yych == 'a') goto yy49;
	goto yy16;
yy35:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'O') goto yy50;
	if (yych == 'o') goto yy50;
	goto yy16;
yy36:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'A') goto yy51;
	if (yych == 'a') goto yy51;
	goto yy16;
yy37:
	YYSKIP();
#line 94 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_NOTICE); }
#line 416 "../../lnav/src/log_level_re.cc"
yy38:
	YYSKIP();
	yych = YYPEEK();
	if (yych <= 'I') {
		if (yych == 'E') goto yy37;
		if (yych <= 'H') goto yy16;
		goto yy52;
	} else {
		if (yych <= 'e') {
			if (yych <= 'd') goto yy16;
			goto yy37;
		} else {
			if (yych == 'i') goto yy52;
			goto yy16;
		}
	}
yy39:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'E') goto yy53;
	if (yych == 'e') goto yy53;
	goto yy16;
yy40:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'T') goto yy54;
	if (yych == 't') goto yy54;
	goto yy16;
yy41:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'T') goto yy55;
	if (yych == 't') goto yy55;
	goto yy16;
yy42:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'C') goto yy56;
	if (yych == 'c') goto yy56;
	goto yy16;
yy43:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'B') goto yy57;
	if (yych == 'b') goto yy57;
	goto yy16;
yy44:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'N') goto yy58;
	if (yych == 'n') goto yy58;
	goto yy16;
yy45:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'I') goto yy60;
	if (yych == 'i') goto yy60;
	goto yy16;
yy46:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'G') goto yy61;
	if (yych == 'g') goto yy61;
	goto yy16;
yy47:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'E') goto yy63;
	if (yych == 'e') goto yy63;
	goto yy16;
yy48:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'R') goto yy64;
	if (yych == 'r') goto yy64;
	goto yy16;
yy49:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'L') goto yy65;
	if (yych == 'l') goto yy65;
	goto yy16;
yy50:
	YYSKIP();
#line 93 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_INFO); }
#line 503 "../../lnav/src/log_level_re.cc"
yy51:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'L') goto yy66;
	if (yych == 'l') goto yy66;
	goto yy16;
yy52:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'C') goto yy67;
	if (yych == 'c') goto yy67;
	goto yy16;
yy53:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'R') goto yy68;
	if (yych == 'r') goto yy68;
	goto yy16;
yy54:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'S') goto yy69;
	if (yych == 's') goto yy69;
	goto yy16;
yy55:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'E') goto yy70;
	if (yych == 'e') goto yy70;
	goto yy16;
yy56:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'E') goto yy71;
	if (yych == 'e') goto yy71;
	goto yy16;
yy57:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'O') goto yy72;
	if (yych == 'o') goto yy72;
	goto yy16;
yy58:
	yyaccept = 2;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych == 'I') goto yy73;
	if (yych == 'i') goto yy73;
yy59:
#line 96 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_WARNING); }
#line 556 "../../lnav/src/log_level_re.cc"
yy60:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'C') goto yy74;
	if (yych == 'c') goto yy74;
	goto yy16;
yy61:
	YYSKIP();
	yych = YYPEEK();
	if (yych <= '1') goto yy62;
	if (yych <= '5') goto yy75;
yy62:
	YYSTAGP(debug_level);
#line 76 "../../lnav/src/log_level_re.re"
	{
         if (debug_level == nullptr) {
             RET(LEVEL_DEBUG);
         }
         switch (*debug_level) {
         case '2':
             RET(LEVEL_DEBUG2);
         case '3':
             RET(LEVEL_DEBUG3);
         case '4':
             RET(LEVEL_DEBUG4);
         case '5':
             RET(LEVEL_DEBUG5);
         default:
             RET(LEVEL_DEBUG);
         }
     }
#line 588 "../../lnav/src/log_level_re.cc"
yy63:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'C') goto yy76;
	if (yych == 'c') goto yy76;
	goto yy16;
yy64:
	YYSKIP();
	goto yy33;
yy65:
	YYSKIP();
#line 100 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_FATAL); }
#line 602 "../../lnav/src/log_level_re.cc"
yy66:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'I') goto yy77;
	if (yych == 'i') goto yy77;
	goto yy16;
yy67:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'E') goto yy37;
	if (yych == 'e') goto yy37;
	goto yy16;
yy68:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'E') goto yy78;
	if (yych == 'e') goto yy78;
	goto yy16;
yy69:
	YYSKIP();
#line 95 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_STATS); }
#line 625 "../../lnav/src/log_level_re.cc"
yy70:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'M') goto yy50;
	if (yych == 'm') goto yy50;
	goto yy16;
yy71:
	YYSKIP();
#line 75 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_TRACE); }
#line 636 "../../lnav/src/log_level_re.cc"
yy72:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'S') goto yy56;
	if (yych == 's') goto yy56;
	goto yy16;
yy73:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'N') goto yy79;
	if (yych == 'n') goto yy79;
	goto yy16;
yy74:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'A') goto yy80;
	if (yych == 'a') goto yy80;
	goto yy16;
yy75:
	YYSKIP();
	goto yy62;
yy76:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'A') goto yy81;
	if (yych == 'a') goto yy81;
	goto yy16;
yy77:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'D') goto yy82;
	if (yych == 'd') goto yy82;
	goto yy16;
yy78:
	YYSKIP();
#line 99 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_CRITICAL); }
#line 674 "../../lnav/src/log_level_re.cc"
yy79:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'G') goto yy83;
	if (yych == 'g') goto yy83;
	goto yy16;
yy80:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'L') goto yy84;
	if (yych == 'l') goto yy84;
	goto yy16;
yy81:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'T') goto yy85;
	if (yych == 't') goto yy85;
	goto yy16;
yy82:
	YYSKIP();
#line 101 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_INVALID); }
#line 697 "../../lnav/src/log_level_re.cc"
yy83:
	YYSKIP();
	goto yy59;
yy84:
	YYSKIP();
#line 98 "../../lnav/src/log_level_re.re"
	{ RET(LEVEL_CRITICAL); }
#line 705 "../../lnav/src/log_level_re.cc"
yy85:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'I') goto yy86;
	if (yych != 'i') goto yy16;
yy86:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'O') goto yy87;
	if (yych != 'o') goto yy16;
yy87:
	YYSKIP();
	yych = YYPEEK();
	if (yych == 'N') goto yy83;
	if (yych == 'n') goto yy83;
	goto yy16;
}
#line 104 "../../lnav/src/log_level_re.re"

}
